# Generated by Django 5.1.3 on 2024-11-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField()),
                ('body_movements', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('eeg_data', models.FloatField()),
                ('sleeping_hours', models.FloatField()),
                ('blood_oxygen_level', models.FloatField()),
                ('snoring_rate', models.FloatField()),
                ('limb_movement_rate', models.FloatField()),
                ('stress_level', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
